defaults:
  - model: CSM
  - data:
      - IAA
  - _self_

# General config
experiment_name: "CSM_IAA"
num_classes: 6
epochs: 200
learning_rate: 1e-3
batch_size: 32
num_workers: 8
weight_decay: 1e-4
random_seed: 42
# Loss config
lambda_aux: 0.3
temperature: 1
# File path
csv_path: "/home/eslab/Vscode/MultiPatchdopplerMLP/results"
confusion_path: "/home/eslab/Vscode/MultiPatchdopplerMLP/results/confusion"
best_model_path: "/home/eslab/Vscode/MultiPatchdopplerMLP/checkpoints"
